apiVersion: v1
kind: Service
metadata:
  name: a1-interface
  labels:
    app: a1-interface
spec:
  type: NodePort
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  - name: https
    port: 8185
    targetPort: 8185
  selector:
    app: a1-interface

