apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: policy-agent-container
  labels:
    app: policy-agent-container
spec:
  selector:
    matchLabels:
      app: policy-agent-container
  replicas: 1
  template:
    metadata:
      labels:
        app: policy-agent-container
    spec:
      containers:
      - name: master
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/nonrtric-policy-agent:1.0.0
        ports:
        - name: http
          containerPort: 8081
        - name: https
          containerPort: 8433
