---
kind: Namespace
apiVersion: v1
metadata:
  name: nonrtric
  labels:
    name: nonrtric
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: a1-interface-osc
  namespace: nonrtric
  labels:
    app: a1-sim
spec:
  selector:
    matchLabels:
      app: a1-sim
  replicas: 2
  serviceName: a1-sim
  template:
    metadata:
      labels:
        app: a1-sim
    spec:
      containers:
      - name: master
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/a1-simulator:2.1.0
        ports:
        - name: http
          containerPort: 8085
        - name: https
          containerPort: 8185
        env:
        - name: A1_VERSION
          value: OSC_2.1.0
        - name: ALLOW_HTTP
          value: "true"
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: a1-interface-std
  namespace: nonrtric
  labels:
    app: a1-sim
spec:
  selector:
    matchLabels:
      app: a1-sim
  replicas: 2
  serviceName: a1-sim
  template:
    metadata:
      labels:
        app: a1-sim
    spec:
      containers:
      - name: master
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/a1-simulator:2.1.0
        ports:
        - name: http
          containerPort: 8085
        - name: https
          containerPort: 8185
        env:
        - name: A1_VERSION
          value: STD_1.1.3
        - name: ALLOW_HTTP
          value: "true"
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: a1-interface-std-v2
  namespace: nonrtric
  labels:
    app: a1-sim
spec:
  selector:
    matchLabels:
      app: a1-sim
  replicas: 2
  serviceName: a1-sim
  template:
    metadata:
      labels:
        app: a1-sim
    spec:
      containers:
      - name: master
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/a1-simulator:2.1.0
        ports:
        - name: http
          containerPort: 8085
        - name: https
          containerPort: 8185
        env:
        - name: A1_VERSION
          value: STD_2.0.0
        - name: ALLOW_HTTP
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: a1-sim
  namespace: nonrtric
  labels:
    app: a1-sim
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8085
    targetPort: 8085
  - name: https
    port: 8185
    targetPort: 8185
  selector:
    app: a1-sim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: a1-interface-std
#   namespace: nonrtric
#   labels:
#     app: a1-interface-std
# spec:
#   type: NodePort
#   ports:
#   - name: http
#     port: 8085
#     targetPort: 8085
#   - name: https
#     port: 8185
#     targetPort: 8185
#   selector:
#     app: a1-interface-std
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: policy-agent-container
  namespace: nonrtric
  labels:
    app: policy-agent-container
spec:
  selector:
    matchLabels:
      app: policy-agent-container
  replicas: 1
  template:
    metadata:
      labels:
        app: policy-agent-container
    spec:
      containers:
      - name: master
        image: nexus3.onap.org:10003/onap/ccsdk-oran-a1policymanagementservice:1.1.1-STAGING-latest
        ports:
        - name: http
          containerPort: 8081
        - name: https
          containerPort: 8433
        volumeMounts:
        - name: "config"
          mountPath: "/opt/app/policy-agent/data/application_configuration.json"
          subPath: "application_configuration.json"
      volumes:
        - name: "config"
          configMap:
            name: "config"
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: config
  namespace: nonrtric
data:
  # example of a complex property defined using --from-file
  application_configuration.json: |-
    {
      "config": {
          "ric": [
            {
                "name": "ric1",
                "baseUrl": "https://a1-interface-osc-0.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            },
            {
                "name": "ric2",
                "baseUrl": "https://a1-interface-osc-1.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            },
            {
                "name": "ric3",
                "baseUrl": "https://a1-interface-std-0.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            },
            {
                "name": "ric4",
                "baseUrl": "https://a1-interface-std-1.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            },
            {
                "name": "ric5",
                "baseUrl": "https://a1-interface-std-v2-0.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            },
            {
                "name": "ric6",
                "baseUrl": "https://a1-interface-std-v2-1.a1-sim:8185/",
                "managedElementIds": [
                  "kista_1",
                  "kista_2"
                ]
            }
          ]
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: policy-agent-container
  namespace: nonrtric
  labels:
    app: policy-agent-container
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: https
    port: 8433
    targetPort: 8433
  selector:
    app: policy-agent-container

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: controlpanel
  namespace: nonrtric
  labels:
    app: controlpanel
spec:
  selector:
    matchLabels:
      app: controlpanel
  replicas: 1
  template:
    metadata:
      labels:
        app: controlpanel
    spec:
      containers:
      - name: master
        image: nexus3.o-ran-sc.org:10004/o-ran-sc/nonrtric-controlpanel:2.1.1
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: controlpanel
  namespace: nonrtric
  labels:
    app: controlpanel
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8082
    targetPort: 8082
  selector:
    app: controlpanel