echo "apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: echo-plaintext
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - port: 9000
    backend:
      serviceName: registry
      servicePort: 5000
" | kubectl apply -f -
tcpingress.configuration.konghq.com/echo-plaintext created
