apiVersion: v1
kind: Service
metadata:
  name: policy-agent-container
  namespace: nonrtric
  labels:
    app: policy-agent-container
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: https
    port: 8433
    targetPort: 8433
  selector:
    app: policy-agent-container

